"""The exported block: one markdown shape for every host.

Everything host-specific (a Cursor frontmatter, where the block sits in a
CLAUDE.md) belongs to :mod:`writers`. This module only turns rules into
text and hashes that text so the manifest can tell when the vault moved on.
"""
from __future__ import annotations

import hashlib
from typing import Sequence

from mnemo.core.export.select import ExportRule

START_MARKER = "<!-- mnemo:start"
END_MARKER = "<!-- mnemo:end -->"
TOKEN_WARN = 4000


def render_entry(rule: ExportRule) -> str:
    head = f"### {rule.name}  `{rule.slug}`"
    if rule.universal:
        head += " (universal)"
    parts = [head, rule.body.rstrip()]
    if rule.quote:
        parts.append(f'> you said: "{rule.quote}"')
    return "\n".join(parts) + "\n"


def render_block(rules: Sequence[ExportRule], *, project: str, today: str) -> str:
    n_uni = sum(1 for r in rules if r.universal)
    header = (
        f"{START_MARKER} — generated by `mnemo export` on {today}; "
        "edit the vault, not this block -->"
    )
    title = (
        f"## Rules mnemo learned from you (project: {project}, "
        f"{len(rules)} rule{'s' if len(rules) != 1 else ''}, {n_uni} universal)"
    )
    body = "\n".join(render_entry(r) for r in rules)
    return "\n".join([header, title, "", body.rstrip(), END_MARKER]) + "\n"


def entry_hash(rule: ExportRule) -> str:
    return hashlib.sha256(render_entry(rule).encode("utf-8")).hexdigest()


def estimated_tokens(text: str) -> int:
    return len(text) // 4
