"""The exported block: one markdown shape for every host.

Everything host-specific (a Cursor frontmatter, where the block sits in a
CLAUDE.md) belongs to :mod:`writers`. This module only turns rules into
text and hashes that text so the manifest can tell when the vault moved on.

Two formats (#129). The default is *compact*: each rule is its heading, the
first paragraph of its body — the sentence the extractor leads with, before
the ``**Why:**`` / ``**How to apply:**`` sections — and the ``> you said:``
quote. ``full=True`` writes the whole body. Measured on a real 26-rule
project the compact block is 2.8k tokens against 6.7k full, and the block
rides on every prompt the host sends, so compact is what an export writes
unless asked otherwise; the host can still read any rule in full through
the ``read_mnemo_rule`` MCP tool.
"""
from __future__ import annotations

import hashlib
import re
from typing import Sequence

from mnemo.core.export.select import ExportRule

START_MARKER = "<!-- mnemo:start"
END_MARKER = "<!-- mnemo:end -->"
TOKEN_WARN = 4000

_PARAGRAPH_BREAK = re.compile(r"\n[ \t]*\n")

COMPACT_NOTE = (
    "_Each rule is its lead sentence and your quote. Read one in full with the "
    "`read_mnemo_rule` MCP tool, or write the full text with `mnemo export --full`._"
)


def first_paragraph(body: str) -> str:
    """The text up to the first blank line, stripped; a whitespace-only line
    counts as blank. A body with no blank line is returned whole."""
    return _PARAGRAPH_BREAK.split(body.strip(), maxsplit=1)[0].strip()


def render_entry(rule: ExportRule, *, full: bool = False) -> str:
    name = rule.name.replace("`", "'")
    head = f"### {name}  `{rule.slug}`"
    if rule.universal:
        head += " (universal)"
    body = rule.body.rstrip() if full else first_paragraph(rule.body)
    # Neutralise any marker-like sequence in the body: a rule body containing
    # a literal "<!-- mnemo:end -->" (or "<!-- mnemo:start") would otherwise
    # truncate the managed block for the host and break the writer. Uses a
    # zero-width space so the text still reads correctly to a human.
    body = body.replace("<!-- mnemo:", "<!--​ mnemo:")
    parts = [head] + ([body] if body else [])
    if rule.quote:
        parts.append(f'> you said: "{rule.quote}"')
    return "\n".join(parts) + "\n"


def render_block(rules: Sequence[ExportRule], *, project: str, today: str,
                 full: bool = False) -> str:
    n_uni = sum(1 for r in rules if r.universal)
    header = (
        f"{START_MARKER} — generated by `mnemo export` on {today}; "
        "edit the vault, not this block -->"
    )
    title = (
        f"## Rules mnemo learned from you (project: {project}, "
        f"{len(rules)} rule{'s' if len(rules) != 1 else ''}, {n_uni} universal)"
    )
    if not rules:
        return "\n".join([header, "", title, "", END_MARKER]) + "\n"
    body = "\n".join(render_entry(r, full=full) for r in rules)
    lead = [header, "", title, ""] if full else [header, "", title, "", COMPACT_NOTE, ""]
    return "\n".join(lead + [body.rstrip(), "", END_MARKER]) + "\n"


def entry_hash(rule: ExportRule, *, full: bool = False) -> str:
    return hashlib.sha256(render_entry(rule, full=full).encode("utf-8")).hexdigest()


def estimated_tokens(text: str) -> int:
    return len(text) // 4
