"""A second recall harness, built from the sessions rules were extracted from.

:mod:`mnemo.core.mcp.recall` measures retrieval against the access log: a
``list_rules_by_topic`` followed by a ``read_mnemo_rule`` of something it
returned is a rule the model went and fetched, which is as close to a relevance
label as telemetry gets. It is also capped by something no setting can raise —
the entire log holds 71 reads, which dedup to 56 cases. Widening the pairing
window adds nothing; only more use adds cases. 56 is too few to separate a real
ranking improvement from noise, and ranking is the next thing that has to be
worked on.

Every rule already records the sessions it came from. That is ground truth by
construction, and the transcripts of those sessions hold the prompts that
produced the work — a query shaped exactly like what reflex scores at
``UserPromptSubmit``, against an answer nobody had to label.

**This does not replace the telemetry harness, and its absolute numbers are not
comparable to it.** The rule was written from the session, so anything drawn
from that session shares vocabulary with it and scores higher than a stranger's
prompt would. The prompt leaks least — it did not author the rule's text, the
work did — but it still leaks. What survives the bias is the *delta*: the
inflation is the same for every ranking variant measured against the same
cases, so "did this change help?" stays answerable even though "how good is it?"
does not. Read ``recall`` for the second question.

Two deliberate narrowings, both to stop the harness manufacturing failures that
retrieval never caused:

- **One case per session, not per prompt.** A rule comes out of part of a
  session's work. Scoring every prompt in that session against every rule it
  produced marks a mid-task prompt wrong for not predicting a rule the work had
  not reached yet.
- **The first substantive prompt.** It is where the session states its intent,
  which is the part the extracted rules are actually about.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Optional, TypedDict

# Below this, a prompt has too little to rank on — the same floor reflex applies
# at `minQueryTokens` before it will score anything at all.
_MIN_PROMPT_TOKENS = 4

# `user` turns that nobody typed. Slash-command output, hook context and
# background-task notifications are all replayed into the transcript as user
# messages, and a tool_result block is the transcript's own plumbing. Scoring
# any of them measures retrieval against text the session's author never wrote
# — and the long, vocabulary-rich ones (task notifications especially) land
# early and quietly become the query for an entire case.
_SYNTHETIC = re.compile(
    r"<(local-command-stdout|local-command-caveat|command-name|command-message"
    r"|command-args|system-reminder|task-notification|task-id|tool-use-id"
    r"|output-file|user-prompt-submit-hook)>"
    r"|^Caveat: The messages below were generated by the user",
    re.I | re.M,
)

_RANKS_REPORTED = (3, 5, 10)


class Case(TypedDict):
    id: str
    project: str
    session_id: str
    prompt: str
    expect_slugs: list[str]


class CaseResult(TypedDict):
    id: str
    project: str
    best_rank: Optional[int]
    ranks: dict[str, Optional[int]]
    expected: int
    candidate_count: int
    elapsed_ms: float


def bootstrap_cases(
    vault_root: Path, *, projects_root: Optional[Path] = None
) -> list[Case]:
    """One case per extraction session that still has a transcript on disk.

    Sessions without one are skipped rather than approximated from the
    briefing: the briefing was written by the same model from the same material
    as the rule, so it leaks far more than the prompt does, and mixing the two
    sources would make the harness's bias depend on which sessions happened to
    be pruned.
    """
    vault_root = Path(vault_root)
    if projects_root is None:
        projects_root = Path.home() / ".claude" / "projects"

    transcripts = _transcripts_by_session(Path(projects_root))
    cases: list[Case] = []
    for (project, session_id), slugs in sorted(_rules_by_session(vault_root).items()):
        path = transcripts.get(session_id)
        if path is None:
            continue
        prompt = _first_substantive_prompt(path)
        if prompt is None:
            continue
        cases.append({
            "id": f"{project}:{session_id}",
            "project": project,
            "session_id": session_id,
            "prompt": prompt,
            "expect_slugs": sorted(slugs),
        })
    return cases


def _rules_by_session(vault_root: Path) -> dict[tuple[str, str], set[str]]:
    """Map (project, session id) → the slugs extracted from that session.

    Keyed off ``sources:`` entries whose file is still in the vault. A source
    that points nowhere is not evidence of anything, and the doctor already
    reports those as their own fault.
    """
    from mnemo.core.filters import derive_rule_slug, parse_frontmatter

    out: dict[tuple[str, str], set[str]] = {}
    for md in sorted(vault_root.glob("shared/*/*.md")):
        if md.parent.name in ("_archive", "_inbox"):
            continue
        try:
            fm = parse_frontmatter(md.read_text(encoding="utf-8", errors="replace"))
        except Exception:
            continue
        slug = derive_rule_slug(fm, md.stem)
        for src in fm.get("sources") or []:
            src = str(src)
            if not (vault_root / src).is_file():
                continue
            parts = Path(src).parts
            # bots/<project>/briefings/sessions/<session id>.md
            if len(parts) < 2 or parts[0] != "bots":
                continue
            out.setdefault((parts[1], Path(src).stem), set()).add(slug)
    return out


def _transcripts_by_session(projects_root: Path) -> dict[str, Path]:
    """Every transcript on disk, keyed by session id (the filename stem)."""
    found: dict[str, Path] = {}
    try:
        dirs = [d for d in projects_root.iterdir() if d.is_dir()]
    except OSError:
        return found
    for d in dirs:
        try:
            for f in d.glob("*.jsonl"):
                found.setdefault(f.stem, f)
        except OSError:
            continue
    return found


def _first_substantive_prompt(path: Path) -> Optional[str]:
    """The session's opening human prompt, or None when it has none worth ranking."""
    try:
        raw_lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None
    for raw in raw_lines:
        raw = raw.strip()
        if not raw:
            continue
        try:
            entry = json.loads(raw)
        except ValueError:
            continue
        if not isinstance(entry, dict) or entry.get("type") != "user":
            continue
        text = _plain_text(((entry.get("message") or {}) if isinstance(
            entry.get("message"), dict) else {}).get("content"))
        if text is None:
            continue
        if _SYNTHETIC.search(text):
            continue
        if len(text.split()) < _MIN_PROMPT_TOKENS:
            continue
        return text
    return None


def _plain_text(content: Any) -> Optional[str]:
    """Human-typed text out of a message body, or None when there is none.

    A list body carrying ``tool_result`` blocks is a transcript mechanism
    wearing a user turn, so it yields nothing rather than its text.
    """
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return None
    parts: list[str] = []
    for block in content:
        if not isinstance(block, dict):
            continue
        if block.get("type") != "text":
            return None  # tool_result and friends: not a prompt at all
        parts.append(str(block.get("text") or ""))
    text = " ".join(parts).strip()
    return text or None


def run_case(vault_root: Path, case: Case, index: Optional[dict] = None) -> CaseResult:
    """Score the case's prompt against the reflex index; rank every expected rule.

    Deliberately the *reflex* scorer rather than ``list_rules_by_topic``: the
    query is free prompt text with no topic attached, which is the path a real
    prompt takes, and BM25F ranking is the thing ranking work will change. The
    triple-gate is not applied — this measures the ordering, not whether the
    gates chose to speak.
    """
    import time

    from mnemo.core.reflex import bm25
    from mnemo.core.reflex.index import load_index
    from mnemo.core.reflex.tokenizer import tokenize_query

    if index is None:
        index = load_index(vault_root) or {"docs": {}, "postings": {}}

    docs = index.get("docs") or {}
    candidates = [
        slug for slug, doc in docs.items()
        if case["project"] in (doc.get("projects") or []) or doc.get("universal")
    ]

    t0 = time.perf_counter()
    scored = bm25.score_docs(
        index,
        query_tokens=tokenize_query(case["prompt"]),
        candidate_slugs=candidates,
        weights=bm25.DEFAULT_WEIGHTS,
        params=bm25.DEFAULT_PARAMS,
    )
    elapsed_ms = (time.perf_counter() - t0) * 1000

    order = {slug: i + 1 for i, (slug, _score) in enumerate(scored)}
    ranks: dict[str, Optional[int]] = {s: order.get(s) for s in case["expect_slugs"]}
    present = [r for r in ranks.values() if r is not None]
    return {
        "id": case["id"],
        "project": case["project"],
        "best_rank": min(present) if present else None,
        "ranks": ranks,
        "expected": len(case["expect_slugs"]),
        "candidate_count": len(candidates),
        "elapsed_ms": round(elapsed_ms, 3),
    }


def aggregate(results: list[CaseResult]) -> dict:
    """Roll results up under two metrics, because they answer different questions.

    ``any_at_k`` counts sessions where at least one expected rule surfaced — the
    optimistic view, and the one comparable in spirit to the telemetry
    harness's primacy. ``recall_at_k`` counts expected *rules* found out of all
    expected, which is the number ranking work has to move: a change that lifts
    one rule and buries three looks fine under the first and bad under the
    second.
    """
    total = len(results)
    expected_total = sum(r["expected"] for r in results)
    report: dict = {
        "harness": "sessions",
        "cases": total,
        "expected_rules": expected_total,
    }
    for k in _RANKS_REPORTED:
        any_hits = sum(
            1 for r in results
            if r["best_rank"] is not None and r["best_rank"] <= k
        )
        found = sum(
            1 for r in results for rank in r["ranks"].values()
            if rank is not None and rank <= k
        )
        report[f"any_at_{k}"] = any_hits
        report[f"any_rate_at_{k}"] = round(any_hits / total, 4) if total else 0.0
        report[f"recall_at_{k}"] = (
            round(found / expected_total, 4) if expected_total else 0.0
        )
    mrr = (
        sum(1.0 / r["best_rank"] for r in results if r["best_rank"] is not None) / total
        if total else 0.0
    )
    report["mrr"] = round(mrr, 4)
    report["misses"] = [
        r["id"] for r in results
        if r["best_rank"] is None or r["best_rank"] > 10
    ]
    return report
