"""Flatten Claude Code jsonl session events into a plain-text transcript.

Extracted from ``mnemo.core.extract.prompts.build_briefing_prompt`` in
v0.9 PR F2 — it's event-parsing logic, not prompt composition (SRP fix).
The briefing caller now composes:

    transcript = flatten_transcript_events(events)
    prompt = build_briefing_prompt(transcript)
"""
from __future__ import annotations

import re
from typing import Any, Optional


def flatten_transcript_events(events: list[dict]) -> str:
    """Render a list of Claude Code jsonl events into a flat text transcript.

    Tolerates malformed events: non-dict entries, missing ``message``,
    string-or-list ``content``, and unknown content-block types are all
    skipped without raising. ``tool_result`` blocks longer than 400
    characters are truncated with an ellipsis to keep the prompt within
    sensible token budgets.
    """
    lines: list[str] = []
    for ev in events:
        if not isinstance(ev, dict):
            continue
        etype = str(ev.get("type") or "")
        msg = ev.get("message") or {}
        role = str(msg.get("role") or etype or "?")
        content = msg.get("content")
        text = ""
        if isinstance(content, str):
            text = content
        elif isinstance(content, list):
            parts: list[str] = []
            for block in content:
                if not isinstance(block, dict):
                    continue
                btype = block.get("type")
                if btype == "text":
                    parts.append(str(block.get("text") or ""))
                elif btype == "tool_use":
                    name = block.get("name") or "tool"
                    parts.append(f"[tool_use: {name}]")
                elif btype == "tool_result":
                    preview = str(block.get("content") or "")
                    if len(preview) > 400:
                        preview = preview[:400] + "…"
                    parts.append(f"[tool_result: {preview}]")
            text = "\n".join(p for p in parts if p)
        if not text.strip():
            continue
        lines.append(f"[{role}] {text}")

    return "\n\n".join(lines)


# `user` turns that nobody typed. Slash-command output, hook context and
# background-task notifications are all replayed into the transcript as user
# messages, and a tool_result block is the transcript's own plumbing. Both the
# recall harness and the briefing's corrections pass must ignore them, so the
# pattern lives here and both import it.
SYNTHETIC_TURN = re.compile(
    r"<(local-command-stdout|local-command-caveat|command-name|command-message"
    r"|command-args|system-reminder|task-notification|task-id|tool-use-id"
    r"|output-file|user-prompt-submit-hook)>"
    r"|^Caveat: The messages below were generated by the user",
    re.I | re.M,
)


def plain_user_text(content: Any) -> Optional[str]:
    """Human-typed text out of a message body, or None when there is none.

    A list body carrying ``tool_result`` blocks is a transcript mechanism
    wearing a user turn, so it yields nothing rather than its text.
    """
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return None
    parts: list[str] = []
    for block in content:
        if not isinstance(block, dict):
            continue
        if block.get("type") != "text":
            return None  # tool_result and friends: not a prompt at all
        parts.append(str(block.get("text") or ""))
    text = " ".join(parts).strip()
    return text or None


def user_turns(events: list) -> list[str]:
    """The user's own turns, verbatim and in order.

    Everything the harness replays as a ``user`` message (task notifications,
    hook context, slash-command output, tool results) is excluded — a
    correction can only be evidenced by words the person actually typed.
    """
    out: list[str] = []
    for ev in events:
        if not isinstance(ev, dict) or ev.get("type") != "user":
            continue
        msg = ev.get("message")
        if not isinstance(msg, dict):
            continue
        text = plain_user_text(msg.get("content"))
        if text is None or SYNTHETIC_TURN.search(text):
            continue
        out.append(text)
    return out
