"""Per-briefing read telemetry — ``record_briefing_read`` (channels round).

The session-start envelope logged only ``included_briefing: true``, so which
of the briefings on disk a session actually received was unrecoverable. These
tests pin the row that makes it recoverable, and the guarantees a recorder
running on every session start must keep: cheap, never raising, and separate
from the MCP access log whose rotation window ``mnemo recall`` depends on.
"""
from __future__ import annotations

import inspect
import json
from pathlib import Path

import pytest

from mnemo.core import briefing
from mnemo.core.mcp import access_log


@pytest.fixture
def telemetry_on(monkeypatch):
    monkeypatch.setattr(access_log, "_load_telemetry_config", lambda: (True, 1_048_576))


def _write_briefing(
    vault: Path,
    project: str,
    session_id: str,
    *,
    date: str = "2026-09-14",
    agent: str | None = None,
    body: str = "## TL;DR\n\nDid the thing.\n",
) -> Path:
    path = vault / "bots" / project / "briefings" / "sessions" / f"{session_id}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "---\n"
        "type: briefing\n"
        f"agent: {agent or project}\n"
        f"session_id: {session_id}\n"
        f"date: {date}\n"
        "duration_minutes: 12\n"
        "---\n\n"
        f"{body}",
        encoding="utf-8",
    )
    return path


def _rows(vault: Path) -> list[dict]:
    log = vault / ".mnemo" / "briefing-log.jsonl"
    if not log.exists():
        return []
    return [json.loads(line) for line in log.read_text(encoding="utf-8").splitlines() if line]


def test_signature_is_the_contract():
    params = list(inspect.signature(briefing.record_briefing_read).parameters)
    assert params == ["vault_root", "record"]
    # Reachable through the briefing API the injector picks with.
    assert briefing.record_briefing_read is access_log.record_briefing_read


def test_row_names_the_briefing_the_picker_returned(tmp_path, telemetry_on):
    _write_briefing(tmp_path, "mnemo", "aaaa", date="2026-09-10")
    newest = _write_briefing(tmp_path, "mnemo", "bbbb", date="2026-09-14")

    rec = briefing.pick_latest_briefing(tmp_path, "mnemo")
    briefing.record_briefing_read(tmp_path, rec)

    (row,) = _rows(tmp_path)
    assert row["path"] == newest.relative_to(tmp_path).as_posix()
    assert row["path"] == "bots/mnemo/briefings/sessions/bbbb.md"
    assert row["project"] == "mnemo"
    assert row["session_id"] == "bbbb"
    assert row["date"] == "2026-09-14"
    assert row["timestamp"].endswith("Z")
    assert set(row) == {
        "timestamp", "project", "path", "session_id", "date", "body_bytes", "body_sha256",
    }


def test_hash_and_size_cover_exactly_the_injected_text(tmp_path, telemetry_on):
    import hashlib

    _write_briefing(tmp_path, "mnemo", "s1", body="## TL;DR\n\nnão é ascii — ok\n\n\n")
    rec = briefing.pick_latest_briefing(tmp_path, "mnemo")
    briefing.record_briefing_read(tmp_path, rec)

    # session_start injects ``rec.body.rstrip()``; the row must describe that.
    injected = rec.body.rstrip().encode("utf-8")
    (row,) = _rows(tmp_path)
    assert row["body_bytes"] == len(injected)
    assert row["body_sha256"] == "sha256:" + hashlib.sha256(injected).hexdigest()[:16]


def test_rewritten_briefing_at_the_same_path_is_distinguishable(tmp_path, telemetry_on):
    path = _write_briefing(tmp_path, "mnemo", "s1", body="first version\n")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    _write_briefing(tmp_path, "mnemo", "s1", body="regenerated by mnemo learn\n")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))

    a, b, c = _rows(tmp_path)
    assert a["path"] == b["path"] == c["path"] == path.relative_to(tmp_path).as_posix()
    assert a["body_sha256"] == b["body_sha256"]
    assert c["body_sha256"] != a["body_sha256"]


def test_project_is_the_directory_read_not_the_frontmatter_agent(tmp_path, telemetry_on):
    # A briefing migrated out of a worktree namespace keeps its old agent line.
    _write_briefing(tmp_path, "mnemo", "s1", agent="mnemo-wt-225")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    (row,) = _rows(tmp_path)
    assert row["project"] == "mnemo"


def test_session_id_falls_back_to_the_file_stem(tmp_path, telemetry_on):
    path = tmp_path / "bots" / "p" / "briefings" / "sessions" / "stem-id.md"
    path.parent.mkdir(parents=True)
    path.write_text("no frontmatter at all\n", encoding="utf-8")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "p"))
    (row,) = _rows(tmp_path)
    assert row["session_id"] == "stem-id"
    assert row["date"] == ""


def test_does_not_write_the_mcp_access_log(tmp_path, telemetry_on):
    _write_briefing(tmp_path, "mnemo", "s1")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    assert _rows(tmp_path)
    assert not (tmp_path / ".mnemo" / "mcp-access-log.jsonl").exists()


def test_row_size_does_not_grow_with_the_briefing(tmp_path, telemetry_on):
    _write_briefing(tmp_path, "mnemo", "s1", body="x" * 60_000)
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    line = (tmp_path / ".mnemo" / "briefing-log.jsonl").read_bytes()
    assert len(line) < 400
    assert _rows(tmp_path)[0]["body_bytes"] == 60_000


def test_picking_records_nothing(tmp_path, telemetry_on):
    # preempt.py picks briefings too; a pick is not a session reading one.
    _write_briefing(tmp_path, "mnemo", "s1")
    assert briefing.pick_latest_briefing(tmp_path, "mnemo") is not None
    assert not (tmp_path / ".mnemo").exists()


def test_telemetry_off_writes_nothing(tmp_path, monkeypatch):
    monkeypatch.setattr(access_log, "_load_telemetry_config", lambda: (False, 1_048_576))
    _write_briefing(tmp_path, "mnemo", "s1")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    assert not (tmp_path / ".mnemo" / "briefing-log.jsonl").exists()


def test_rotates_at_the_telemetry_size_cap(tmp_path, monkeypatch):
    monkeypatch.setattr(access_log, "_load_telemetry_config", lambda: (True, 200))
    _write_briefing(tmp_path, "mnemo", "s1")
    rec = briefing.pick_latest_briefing(tmp_path, "mnemo")
    for _ in range(3):
        briefing.record_briefing_read(tmp_path, rec)
    log = tmp_path / ".mnemo" / "briefing-log.jsonl"
    assert (tmp_path / ".mnemo" / "briefing-log.jsonl.1").exists()
    assert log.stat().st_size <= 400


def test_accepts_a_string_vault_root(tmp_path, telemetry_on):
    _write_briefing(tmp_path, "mnemo", "s1")
    briefing.record_briefing_read(str(tmp_path), briefing.pick_latest_briefing(tmp_path, "mnemo"))
    assert _rows(tmp_path)[0]["path"] == "bots/mnemo/briefings/sessions/s1.md"


def test_never_raises_when_the_log_cannot_be_written(tmp_path, telemetry_on):
    _write_briefing(tmp_path, "mnemo", "s1")
    (tmp_path / ".mnemo").write_text("a file where the directory should be", encoding="utf-8")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))


def test_never_raises_on_a_malformed_record(tmp_path, telemetry_on):
    briefing.record_briefing_read(tmp_path, None)
    briefing.record_briefing_read(tmp_path, object())
    assert _rows(tmp_path) == []


def test_never_raises_when_config_loading_explodes(tmp_path, monkeypatch):
    def boom():
        raise RuntimeError("config gone")

    monkeypatch.setattr("mnemo.core.config.load_config", boom)
    _write_briefing(tmp_path, "mnemo", "s1")
    briefing.record_briefing_read(tmp_path, briefing.pick_latest_briefing(tmp_path, "mnemo"))
    # _load_telemetry_config fails closed, as the access log always has.
    assert _rows(tmp_path) == []
